version: "3.8"

services:
  django:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/mealhub
    ports:
      - "8000:8000"
    depends_on:
      - pgdb
  pgdb:
    image: postgres
    volumes:
      - data:/var/lib/postgresql/data
    container_name: pgdb
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
volumes:
  data: